version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch-browsers
    steps:
      - checkout
      - run:
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python tests.py
          environment:
            SLACK_SIGNING_SECRET: secret
            LOG_TO_FILE: True
